services:
  client:
    container_name: dp-client
    build:
      context: client
      dockerfile: Dockerfile
      args:
        DISPLAY: ${DISPLAY} # Pass display variable from terminal 
    environment:
      - DISPLAY=${DISPLAY} # Pass display variable from terminal
    volumes:
      # - ./client:/app/client
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 forwarding
      - /usr/share/seclists/Passwords:/usr/share/seclists/Passwords

  backend:
    container_name: dp-backend
    build:
      context: server
      dockerfile: backend/Dockerfile
    depends_on:
      - database
    environment:
      - BACKEND_HOST=0.0.0.0 # Not need to change
      - BACKEND_PORT=4747    # Not need to change
      - DB_USER=agent
      - DB_PASSWORD=SUPERSECUREUNCRACKABLEPASSWORD
      - DB_HOST=dp-database
      - DB_PORT=3306
      - DB_NAME=dp_hashcat

  database:
    build: database
    container_name: dp-database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: unless-stopped
    ports: 
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uagent",
          "-pSUPERSECUREUNCRACKABLEPASSWORD",
        ]
      timeout: 20s
      retries: 10