services:
  client:
    container_name: dp-client
    build:
      context: client
      dockerfile: Dockerfile
      args:
        DISPLAY: ${DISPLAY} # Pass display variable from terminal
    environment:
      - DISPLAY=${DISPLAY} # Pass display variable from terminal
    volumes:
      # - ./client:/app/client
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 forwarding
      - /usr/share/seclists/Passwords:/usr/share/seclists/Passwords

  raspberrypi:
    container_name: emulate-raspberrypi
    build:
      context: raspberry-pi
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - TCP_ADDRESS=0.0.0.0
      - TCP_PORT=4749
      - DEBUG=True

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - BACKEND_HOST=0.0.0.0 # Not need to change
      - BACKEND_PORT=4747    # Not need to change
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=4748
      - DB_USER=agent
      - DB_PASSWORD=SUPERSECUREUNCRACKABLEPASSWORD # This should be changed (remember to change it in database/initialize.sql too
      - DB_HOST=dp-database
      - DB_PORT=3306
      - DB_NAME=dp_hashcat
      - ALLOW_REGISTRATIONS=True # Disable if needed
      - DEBUG=True
      - RESET=True
      - GRPC_URL=0.0.0.0:7777
      - GRPC_TIMEOUT=10s
      - TCP_ADDRESS=0.0.0.0
      - TCP_PORT=4749
    entrypoint: make run

  database:
    build: database
    container_name: dp-database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: unless-stopped
    ports: 
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uagent",
          "-pSUPERSECUREUNCRACKABLEPASSWORD",
        ]
      timeout: 20s
      retries: 10