CREATE USER 'agent' IDENTIFIED BY 'SUPERSECUREUNCRACKABLEPASSWORD';

DROP DATABASE IF EXISTS dp_hashcat;
CREATE DATABASE IF NOT EXISTS dp_hashcat;

-- TABLES 

GRANT SELECT, UPDATE, INSERT, DELETE ON ai_db.* TO 'agent'@'%';
FLUSH PRIVILEGES;