name: Lint client

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  lint:
    name: Run golangci-lint via Makefile
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      HASHCAT_SRC_PATH: ${{ github.workspace }}/external/hashcat
      CGO_CFLAGS: "-I${{ github.workspace }}/external/hashcat/OpenCL -I${{ github.workspace }}/external/hashcat/deps/LZMA-SDK/C -I${{ github.workspace }}/external/hashcat/deps/zlib -I${{ github.workspace }}/external/hashcat/deps/zlib/contrib -I${{ github.workspace }}/external/hashcat/deps/OpenCL-Headers"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libwayland-dev libxkbcommon-dev
          version: 1.0

      - name: Build and Install Hashcat
        run: |
          git clone https://github.com/hashcat/hashcat.git
          cd hashcat
          mkdir /usr/local/lib
          mkdir /usr/local/include/hashcat
          mkdir /usr/local/share/doc
          mkdir /usr/local/share/doc/hashcat
          git checkout v6.1.1
          make install SHARED=1 ENABLE_BRAIN=0
          mkdir -p /usr/local/include/hashcat
          cp deps/LZMA-SDK/C/LzmaDec.h /usr/local/include/hashcat/
          cp deps/LZMA-SDK/C/7zTypes.h /usr/local/include/hashcat/
          cp deps/LZMA-SDK/C/Lzma2Dec.h /usr/local/include/hashcat/
          cp -r ./OpenCL/inc_types.h /usr/local/include/hashcat/
          cp -r ./deps/zlib/contrib /usr/local/include/hashcat
          ln -s /usr/local/lib/libhashcat.so.6.1.1 /usr/local/lib/libhashcat.so
          ln -s /usr/local/lib/libhashcat.so.6.1.1 /usr/lib/libhashcat.so.6.1.1

      - name: Persist Environment Variables
        run: |
          echo "HASHCAT_SRC_PATH=${{ github.workspace }}/hashcat-src" >> $GITHUB_ENV
          echo 'CGO_CFLAGS="-I${{ github.workspace }}/hashcat-src/OpenCL -I${{ github.workspace }}/hashcat-src/deps/LZMA-SDK/C -I${{ github.workspace }}/hashcat-src/deps/zlib -I${{ github.workspace }}/hashcat-src/deps/zlib/contrib -I${{ github.workspace }}/hashcat-src/deps/OpenCL-Headers $CGO_CFLAGS"' >> $GITHUB_ENV

      - name: Verify Installation and Environment Variables
        run: |
          echo "HASHCAT_SRC_PATH=$HASHCAT_SRC_PATH"
          echo "CGO_CFLAGS=$CGO_CFLAGS"
          ls -l /usr/local/include/hashcat
          ls -l /usr/local/lib/libhashcat.so

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Install protoc and dependencies
        run: |
          # Install protoc (Protocol Buffers Compiler)
          sudo apt-get install -y protobuf-compiler

          # Install Go plugin for protoc
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

          # Ensure the bin directory is in PATH for protoc-gen-go and protoc-gen-go-grpc
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      - name: Compile proto files
        run: |
          cd client
          make proto 

      - name: Run golangci-lint:client
        run: |
          cd client
          go mod tidy
          make lint