name: Lint server (FE+BE)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  lint:
    if: github.event.pull_request.draft != true
    
    name: Run golangci-lint via Makefile
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: protobuf-compiler
          version: 1.0

      # sudo apt-get install -y protobuf-compiler
      - name: Install protoc and dependencies
        run: |
          # Install protoc (Protocol Buffers Compiler)

          # Install Go plugin for protoc
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

          # Ensure the bin directory is in PATH for protoc-gen-go and protoc-gen-go-grpc
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      - name: Compile proto files
        run: |
          cd server
          make proto 

      - name: Run golangci-lint:server
        run: |
          cd server
          go mod tidy
          make lint 
