name: Lint with golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - ready_for_review
      - synchronize
      - reopened
      - review_requested
  pull_request_review:
    types:
      - submitted

jobs:
  lint:
    name: Run golangci-lint via Makefile
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      # Step 3: Check for approvals
      - name: Check approval count
        id: approvals
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Count only approved reviews
            const approvals = reviews.filter(review => review.state === 'APPROVED').length;

            core.setOutput('approvals', approvals);
          result-encoding: string

      # Step 4: Conditional step to run linter only if at least 1 approval
      - name: Run golangci-lint if approved
        if: steps.approvals.outputs.approvals >= 1
        run: |
          curl -sSfL https://raw
