name: Replace Markdown Links and Generate PDF

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc texlive-xetex python3 python3-pip
          version: 1.0

      - name: Replace Markdown Links with File Content
        run: |
          #!/bin/bash
          set -e
          set -x

          README_FILE="README.md"
          TEMP_FILE=$(mktemp)

          grep -oP '\[.*?\]\(\K.*?(?=\))' "$README_FILE" | while read -r LINK; do
              if [[ -f "$LINK" && "$LINK" == *.md ]]; then
                  LINK_TEXT=$(grep -oP "\[.*?\]\($LINK\)" "$README_FILE" | sed 's/\[\(.*\)\](.*)/\1/')
                  FILE_CONTENT=$(sed ':a;N;$!ba;s/[\/&]/\\&/g;s/\n/\\n/g' "$LINK")
                  sed "s|\[$LINK_TEXT\]($LINK)|__PLACEHOLDER__|g" "$README_FILE" > "$TEMP_FILE"
                  sed -i "s|__PLACEHOLDER__|$FILE_CONTENT|g" "$TEMP_FILE"
                  mv "$TEMP_FILE" "$README_FILE"
              fi
          done

          cp "$README_FILE" README_links_only.md

      - name: Replace Alerts with HTML Divs
        run: |
          #!/bin/bash
          set -e
          set -x

          README_FILE="README.md"
          TEMP_FILE=$(mktemp)

          sed -i -E '/^> \[!NOTE\]/,/^$/ {
            s/^> \[!NOTE\](.*)$/<div class="alert alert-note">\1/
            :a; n; /^>/! { s/$/<\/div>/; b }; ba
          }' "$README_FILE"

          sed -i -E '/^> \[!TIP\]/,/^$/ {
            s/^> \[!TIP\](.*)$/<div class="alert alert-tip">\1/
            :a; n; /^>/! { s/$/<\/div>/; b }; ba
          }' "$README_FILE"

          sed -i -E '/^> \[!IMPORTANT\]/,/^$/ {
            s/^> \[!IMPORTANT\](.*)$/<div class="alert alert-important">\1/
            :a; n; /^>/! { s/$/<\/div>/; b }; ba
          }' "$README_FILE"

          sed -i -E '/^> \[!WARNING\]/,/^$/ {
            s/^> \[!WARNING\](.*)$/<div class="alert alert-warning">\1/
            :a; n; /^>/! { s/$/<\/div>/; b }; ba
          }' "$README_FILE"

          sed -i -E '/^> \[!CAUTION\]/,/^$/ {
            s/^> \[!CAUTION\](.*)$/<div class="alert alert-caution">\1/
            :a; n; /^>/! { s/$/<\/div>/; b }; ba
          }' "$README_FILE"

      - name: Install WeasyPrint
        run: |
          pip3 install weasyprint

      - name: Convert README.md to PDF with WeasyPrint
        run: |
          mkdir -p docs
          pandoc README.md -o README_temp.html --from markdown --to html
          weasyprint README_temp.html docs/docs.pdf -s docs/styles/main.css
          rm README_temp.html

      - name: Restore README.md to Link Replacement State
        run: |
          mv README_links_only.md README.md

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Replace Markdown links, process alerts, generate PDF, and restore README state"
          file_pattern: README.md docs/docs.pdf
