name: Replace Markdown Links with Content

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  replace-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace Markdown Links with File Content
        run: |
          #!/bin/bash
          set -e
          set -x

          README_FILE="README.md"

          # Find all Markdown links in README.md
          grep -oP '\[.*?\]\(\K.*?(?=\))' "$README_FILE" | while read -r LINK; do
              # Check if the link points to a local Markdown file
              if [[ -f "$LINK" && "$LINK" == *.md ]]; then
                  # Extract the link text for replacement
                  LINK_TEXT=$(grep -oP "\[.*?\]\($LINK\)" "$README_FILE" | sed 's/\[\(.*\)\](.*)/\1/')
          
                  # Get file content and escape sed special characters
                  FILE_CONTENT=$(cat "$LINK" | sed 's/[\/&]/\\&/g')
          
                  # Replace the [Link](path) with a temporary placeholder
                  TEMP_FILE=$(mktemp)
                  sed "s|\[$LINK_TEXT\]($LINK)|__PLACEHOLDER__|g" "$README_FILE" > "$TEMP_FILE"
          
                  # Replace the placeholder with the actual file content, line-by-line safe
                  awk -v replacement="$FILE_CONTENT" '{gsub(/__PLACEHOLDER__/, replacement)}1' "$TEMP_FILE" > "$README_FILE"
                  rm "$TEMP_FILE"
              fi
          done

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Replace Markdown links with file content in README.md"
          file_pattern: README.md
