name: 'Update submodules Branches'

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (UTC)
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  sync:
    if: github.event.pull_request.draft != true

    name: 'Sync Branches'
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: main

      - name: Git Submodule Update
        run: |
          git submodule update --init --remote --recursive
          cd externals/gocat
          git checkout $(git config -f ../../.gitmodules submodule.externals/gocat.branch) || git checkout main
          git pull origin $(git rev-parse --abbrev-ref HEAD)
          cd ../../
          cd externals/hcxtools
          git checkout $(git config -f ../../.gitmodules submodule.externals/hcxtools.branch) || git checkout main
          git pull origin $(git rev-parse --abbrev-ref HEAD)

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update submodules"
          file_pattern: externals/gocat/* externals/hcxtools/*