name: 'Update submodules Branches'

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  sync:
    if: github.event.pull_request.draft != true

    name: 'Sync Branches'
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Update references
      - name: Git Submodule Update
        run: |
          cd externals/gocat
          git pull
          cd ../../
          cd externals/hcxtools
          git pull

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update submodules"
          file_pattern: externals/gocat/* externals/hcxtools/*